import {
  Activity,
  AlertCircle,
  BedDouble,
  Brain,
  CakeSlice,
  Check,
  ChevronLeft,
  ChevronRight,
  Cpu,
  Coffee,
  ChefHat,
  Globe,
  IceCreamBowl,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  PanelsTopLeft,
  Share2,
  Shirt,
  Sliders,
  Smartphone,
  Sparkles,
  Terminal,
  TrendingUp,
  Utensils,
  Users,
  Wrench,
  Store,
  X,
  Zap,
} from 'lucide-react';

// Mapa de nombres de icono (los usados en data/content.js) a componentes lucide-react.
// El proyecto ya dependía de Lucide (vía CDN), por lo que se mantiene esa familia.
const ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'bed-double': BedDouble,
  brain: Brain,
  'cake-slice': CakeSlice,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  cpu: Cpu,
  coffee: Coffee,
  'chef-hat': ChefHat,
  globe: Globe,
  shirt: Shirt,
  'ice-cream-bowl': IceCreamBowl,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'panels-top-left': PanelsTopLeft,
  'share-2': Share2,
  sliders: Sliders,
  smartphone: Smartphone,
  sparkles: Sparkles,
  terminal: Terminal,
  'trending-up': TrendingUp,
  utensils: Utensils,
  users: Users,
  wrench: Wrench,
  store: Store,
  x: X,
  zap: Zap,
};

export default function Icon({ name, className = 'w-5 h-5', strokeWidth = 2, ...props }) {
  const LucideIcon = ICONS[name] || Cpu;
  return <LucideIcon className={className} strokeWidth={strokeWidth} {...props} />;
}
